<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <ItemGroup>
      <Compile Remove="MonoGame.ImGui\**" />
      <EmbeddedResource Remove="MonoGame.ImGui\**" />
      <None Remove="MonoGame.ImGui\**" />
    </ItemGroup>
    <ItemGroup>
        <None Remove="Icon.ico" />
        <None Remove="Icon.bmp" />
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Icon.ico">
            <LogicalName>Icon.ico</LogicalName>
        </EmbeddedResource>
        <EmbeddedResource Include="Icon.bmp">
            <LogicalName>Icon.bmp</LogicalName>
        </EmbeddedResource>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="Arch" Version="2.1.0" />
        <PackageReference Include="FmodForFoxes" Version="3.2.0" />
        <PackageReference Include="FmodForFoxes.Desktop" Version="3.2.0" />
        <PackageReference Include="Google.Apis.Sheets.v4" Version="1.70.0.3819" />
        <PackageReference Include="ImGui.NET" Version="1.91.6.1" />
        <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.5-develop.11" />
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.5-develop.11" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
        <PackageReference Include="RogueSharp" Version="5.0.0-pre4" />
        <PackageReference Include="SadRex" Version="1.0.3" />
        <PackageReference Include="SoftUni.Wintellect.PowerCollections" Version="2.0.0" />
        <PackageReference Include="YamlDotNet" Version="16.3.0" />
    </ItemGroup>
    <ItemGroup>
      <ClCompile Include="Content\crt.fx" />
    </ItemGroup>
    <ItemGroup>
      <Reference Include="MonoJ">
        <HintPath>..\..\SinEditor\MonoJ\bin\Debug\net8.0\MonoJ.dll</HintPath>
      </Reference>
      <Reference Include="wvcs">
        <HintPath>..\..\wv\wvcs\bin\Debug\net8.0\wvcs.dll</HintPath>
      </Reference>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Content\audio\" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="MonoGame.ImGui\MonoGame.ImGui.csproj" />
    </ItemGroup>
    <ItemGroup>
      <None Update="fmod.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fmodL.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fmodstudio.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="fmodstudioL.dll">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    <Target Name="RestoreDotnetTools" BeforeTargets="CollectPackageReferences">
        <Message Text="Restoring dotnet tools (this might take a while depending on your internet speed and should only happen upon building your project for the first time, or after upgrading MonoGame, or clearing your nuget cache)" Importance="High" />
        <Exec Command="dotnet tool restore" />
    </Target>
</Project>